### ISSUE TITLE
retry_on_network_timeout sends duplicate op:start-session

### ISSUE THREAD

**Issue by dpwiz** [ocapn/ocapn-test-suite#5]
Due to how test cases are structured, a party gets session start messages while waiting on promises:
```python
    @retry_on_network_timeout  ## XXX: wraps the whole case in restart
    def test_deliver_promise_pipeline(self):
        """ Can promise pipeline on multiple messages """
        self.remote.setup_session(self.captp_version)  ## XXX: setup_session is a part of the test case

        ## XXX: the actual thing that should be retried?
        car_factory_builder_refr = self.remote.fetch_object(
            b"JadQ0++RzsD4M+40uLxTWVaVqM10DcBJ",
            pipeline=True
        )
    # ...
```
Looks like the method decorator is a wrong granularity here. Perhaps this should be a context (`with restart_on_timeout(): ...`) around the actually restartable blocks.

**Comment by tsyesika** [comment]
It's actually the `setUp` method which runs before each test which can fail. Some tests (handoff tests) need to create multiple connections so those can also fail. We could be a bit more granular. The current way this works though shouldn't lead to getting getting a bootstrap object until the connection is setup.

**Comment by dpwiz** [comment]
The problem I encounter is that a failing test tries to recover by restarting session initiation only to compound on the error, since sending multiple `op:start-session` is against the protocol.

**Comment by tsyesika** [comment]
I looked into this today. The situation was actually not great, the connection was not being re-tried and the issue of messages being sent again over the connection would have been happening.

I think https://github.com/ocapn/ocapn-test-suite/commit/4242a7b096ac3a69adca8d8cf4a98c010b3fc694 should fix this for you, please re-open if this doesn't fix your issue.
